# Generated by Django 4.0.6 on 2022-08-09 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='freshfood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('weight', models.FloatField()),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.FloatField()),
                ('descrption', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
    ]
