# Generated by Django 4.0.6 on 2022-08-09 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_freshfood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='weight',
            new_name='kilos',
        ),
        migrations.RenameField(
            model_name='freshfood',
            old_name='weight',
            new_name='kilos',
        ),
    ]
