# Generated by Django 4.0.6 on 2022-08-09 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_rename_weight_food_kilos_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='freshfood',
            old_name='expiration_date',
            new_name='rottendays',
        ),
    ]
